<ul class="nav navbar-nav side-nav">
<?php foreach ($this->container as $page): ?>
	<?php if ($this->zfcUserIdentity() && $page->getLabel() == 'Logout'): ?>
		<li <?php echo $page->isActive()? 'class="active"' : '' ?>>
	    	<a href="<?= $page->getHref() ?>"><?= $this->translate($page->getLabel()) ?></a>
	   	</li>
   	<?php elseif (!$this->zfcUserIdentity() && $page->getLabel() == 'Login'): ?>
   		<li <?php echo $page->isActive()? 'class="active"' : '' ?>>
	    	<a href="<?= $page->getHref() ?>"><?= $this->translate($page->getLabel()) ?></a>
	   	</li>
	<?php endif ?>
<?php endforeach ?>
</ul>