<!-- Roles -->
<div class="panel panel-default">
    <div class="panel-heading"><?=$this->translate('Roles')?></div>
    <div class="panel-body">
        <p><?=$this->translate("You can manage roles here")?></p>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th><?=$this->translate('ID')?></th>
                <th><?=$this->translate('Name')?></th>
                <th><?=$this->translate('Children') ?></th>
                <th><?=$this->translate('Permissions') ?></th>
                <th><?=$this->translate('Actions')?></th>
            </tr>
        </thead>
        <?php foreach ($this->roles as $role): ?>
        <?php $children = $role->getChildren();?>
            <tr class="">
                <td><?=$role->getId()?></td>
                <td><?=$role->getName()?></td>
                
                <td>
                <?php foreach ($children as $child): ?>
                    <?=$child->getName() . ', '?>
                <?php endforeach ?>
                </td>
                <td>
                <?php foreach ($children as $child): ?>
                    <?php foreach ($child->getPermissions() as $permission): ?>
                        <?=$permission->getName(). ', '?>                            
                    <?php endforeach ?>
                <?php endforeach ?>
                </td>
                <td> 
                    <a href="<?=$this->url('backend/rights/updateRole', array('id' => $role->getId()))?>" class="btn btn-info">
                        <?=$this->translate('Edit')?>
                    </a>
                    <a href="<?=$this->url('backend/rights/deleteRole', array('id' => $role->getId()))?>" class="btn btn-danger">
                        <?=$this->translate('Delete')?>
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
    <div class="panel-footer">
        <a href="<?=$this->url('backend/rights/addRole')?>" class="btn btn-success">
            <?=$this->translate('Add')?>
        </a>
    </div>
</div>