<?php
  $form = $this->form;
  $form->setAttribute('action', $this->url('backoffice/rights/updateRole', array('id' => $this->id)));
  $form->setAttribute('method', 'POST');
  $elements = $form->get('updateRole')->getElements();
  $form->prepare();
?>
<?= $this->form()->openTag($form) ?>
<div class="container">
  <h1><?=$this->escapeHtml($this->translate('Update role'))?></h1>
  <div class="col-xs-5">
    <?php foreach ($elements as $elementName => $element): ?>
      <?php if ($element->getAttribute('type') !== 'hidden'): ?>
        <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $this->formLabel($element) ?></label>
        <?php
        $element->setAttribute('placeholder', 'Name');
        echo $this->formElement($element);
        if ($this->formElementErrors($element)) : ?>
          <?php
          echo $this->formElementErrors()
            ->setMessageOpenFormat('<p class="help-block">')
            ->setMessageSeparatorString('</p><p class="help-block">')
            ->setMessageCloseString('</p>')
            ->render($element);
          ?>
        <?php endif; ?>
        </div>
      <?php else: ?>
        <?=$this->formHidden($element)?>
      <?php endif ?>    
    <?php endforeach ?>
    
    <?= $this->formHidden($this->form->get('update_role_csrf')) ?>
    <?= $this->formSubmit($form->get('submitUpdate')->setAttribute('class', 'btn btn-success'))?>
    <?= $this->form()->closeTag()?>
  </div>
</div>

<script type="text/javascript">
  $('.select2').select2();
</script>